/**:
  controller_manager:
    ros__parameters:
      __ns: skratch
      update_rate: 100  # Hz
      use_sim_time: true

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
